export interface SimulatorScenario {
  id: string;
  label: string;
  command: string;
  output: string[];
  /** Optional file-tree preview shown for generation-related tabs. */
  fileTree?: string[];
}

const SHARED_FOOTER = "✓ Done — {n} change(s) applied.";
const done = (n: number) => SHARED_FOOTER.replace("{n}", String(n));

export const SIMULATOR_SCENARIOS: SimulatorScenario[] = [
  {
    id: "feature",
    label: "Feature",
    command: "pnpm gen feature product",
    output: [
      "Feature Generator",
      "",
      "Feature     product",
      "Page        product",
      "Route       /product",
      "Path key    product",
      "",
      "Changes",
      "",
      "  CREATE src/features/product/types/product.types.ts",
      "  CREATE src/features/product/lib/product.constants.ts",
      "  CREATE src/features/product/hooks/use-product-state.ts",
      "  CREATE src/features/product/components/product-content.tsx",
      "  CREATE src/features/product/types/index.ts",
      "  CREATE src/features/product/lib/index.ts",
      "  CREATE src/features/product/hooks/index.ts",
      "  CREATE src/features/product/components/index.ts",
      "  CREATE src/features/product/view/product-view.tsx",
      "  CREATE src/app/product/page.tsx",
      "  CREATE src/features/product/index.ts",
      "  MODIFY src/routes/paths.ts",
      "",
      done(12),
    ],
    fileTree: [
      "src/features/product/",
      "├── components/",
      "│   ├── product-content.tsx",
      "│   └── index.ts",
      "├── hooks/",
      "│   ├── use-product-state.ts",
      "│   └── index.ts",
      "├── lib/",
      "│   ├── product.constants.ts",
      "│   └── index.ts",
      "├── types/",
      "│   ├── product.types.ts",
      "│   └── index.ts",
      "├── view/",
      "│   └── product-view.tsx",
      "└── index.ts",
      "",
      "src/app/product/page.tsx",
      "src/routes/paths.ts       # + product: \"/product\"",
    ],
  },
  {
    id: "page",
    label: "Page",
    command: "pnpm gen page product-detail --feature product --route /product-detail",
    output: [
      "Page Generator",
      "",
      "Feature     product",
      "Page        product-detail",
      "Route       /product-detail",
      "Path key    productDetail",
      "",
      "Changes",
      "",
      "  CREATE src/features/product/view/product-detail-view.tsx",
      "  CREATE src/app/product-detail/page.tsx",
      "  MODIFY src/features/product/index.ts",
      "  MODIFY src/routes/paths.ts",
      "",
      done(4),
    ],
    fileTree: [
      "src/features/product/",
      "├── view/",
      "│   ├── product-view.tsx",
      "│   └── product-detail-view.tsx",
      "└── index.ts",
      "",
      "src/app/product-detail/page.tsx",
      "src/routes/paths.ts       # + productDetail: \"/product-detail\"",
    ],
  },
  {
    id: "component",
    label: "Component",
    command: "pnpm gen component product-content --feature product",
    output: [
      "Component Generator",
      "",
      "Component   ProductContent",
      "Location    feature: product",
      "",
      "Changes",
      "",
      "  CREATE src/features/product/components/product-content.tsx",
      "  MODIFY src/features/product/components/index.ts",
      "",
      done(2),
    ],
    fileTree: [
      "src/features/product/",
      "└── components/",
      "    ├── index.ts",
      "    ├── product-content.tsx",
      "    └── product-content.tsx",
    ],
  },
  {
    id: "i18n-init",
    label: "i18n Init",
    command: "pnpm gen i18n init",
    output: [
      "i18n Generator",
      "",
      "Locales     th, en",
      "Default     th",
      "Prefix      always",
      "",
      "Changes",
      "",
      "  CREATE src/i18n/routing.ts",
      "  CREATE src/i18n/navigation.ts",
      "  CREATE src/i18n/request.ts",
      "  CREATE src/proxy.ts",
      "  CREATE src/app/[locale]/layout.tsx",
      "  CREATE src/app/[locale]/page.tsx",
      "  CREATE src/components/locale-switcher.tsx",
      "  CREATE locales/th.json",
      "  CREATE locales/en.json",
      "  MODIFY src/components/index.ts",
      "  MODIFY next.config.ts",
      "  DELETE src/app/layout.tsx",
      "  DELETE src/app/page.tsx",
      "  MOVE   src/app/page.tsx → src/app/[locale]/page.tsx",
      "",
      done(14),
    ],
    fileTree: [
      "src/i18n/",
      "├── routing.ts",
      "├── navigation.ts",
      "└── request.ts",
      "",
      "src/app/[locale]/",
      "├── layout.tsx",
      "└── page.tsx",
      "",
      "src/components/locale-switcher.tsx",
      "locales/th.json",
      "locales/en.json",
    ],
  },
  {
    id: "i18n-remove",
    label: "i18n Remove",
    command: "pnpm gen i18n remove",
    output: [
      "i18n removal analysis",
      "",
      "Locales        th, en",
      "Default locale th",
      "Translation calls 0",
      "Files using i18n 0",
      "Dynamic calls    0",
      "",
      "! Removing i18n may modify application source code.",
      "",
      "i18n removal",
      "",
      "Changes",
      "",
      "  CREATE src/app/layout.tsx",
      "  CREATE src/app/page.tsx",
      "  DELETE src/app/[locale]/layout.tsx",
      "  DELETE src/app/[locale]/page.tsx",
      "  DELETE src/i18n/routing.ts",
      "  DELETE src/i18n/navigation.ts",
      "  DELETE src/i18n/request.ts",
      "  DELETE src/proxy.ts",
      "  DELETE src/components/locale-switcher.tsx",
      "  DELETE locales/th.json",
      "  DELETE locales/en.json",
      "  MODIFY src/components/index.ts",
      "  MODIFY next.config.ts",
      "",
      done(11),
    ],
  },
  {
    id: "theme-init",
    label: "Theme Init",
    command: "pnpm gen theme init",
    output: [
      "Theme Generator",
      "",
      "Modes    light / dark / system",
      "Library  next-themes",
      "",
      "Changes",
      "",
      "  CREATE src/providers/theme-provider.tsx",
      "  CREATE src/components/theme-toggle.tsx",
      "  MODIFY src/providers/index.ts",
      "  MODIFY src/components/index.ts",
      "  MODIFY src/app/layout.tsx",
      "  MODIFY src/app/globals.css",
      "  MODIFY src/app/page.tsx",
      "",
      done(7),
    ],
    fileTree: [
      "src/providers/",
      "├── theme-provider.tsx",
      "└── index.ts",
      "",
      "src/components/",
      "├── theme-toggle.tsx",
      "└── index.ts",
      "",
      "src/app/layout.tsx",
      "src/app/globals.css",
    ],
  },
  {
    id: "theme-remove",
    label: "Theme Remove",
    command: "pnpm gen theme remove",
    output: [
      "Theme removal analysis",
      "",
      "Files using theme 2",
      "",
      "! Removing the theme system may modify application source code.",
      "",
      "Theme removal",
      "",
      "Changes",
      "",
      "  DELETE src/providers/theme-provider.tsx",
      "  DELETE src/components/theme-toggle.tsx",
      "  MODIFY src/providers/index.ts",
      "  MODIFY src/components/index.ts",
      "  MODIFY src/app/layout.tsx",
      "  MODIFY src/app/page.tsx",
      "  MODIFY src/app/globals.css",
      "",
      done(7),
    ],
  },
  {
    id: "routes-check",
    label: "Routes Check",
    command: "pnpm gen routes check",
    output: [
      "Routes Check",
      "",
      "✓ No hardcoded internal navigation paths found.",
    ],
  },
  {
    id: "doctor",
    label: "Doctor",
    command: "pnpm gen doctor",
    output: [
      "Next Starter Doctor",
      "",
      "✓ Next.js detected",
      "✓ App Router detected",
      "✓ TypeScript configured",
      "✓ Feature root exists",
      "✓ Centralized route registry exists",
      "✓ No duplicated static routes",
      "✓ No obvious hardcoded internal navigation",
      "",
      "i18n:",
      "✓ disabled",
      "",
      "Theme:",
      "✓ disabled",
      "",
      "0 errors, 0 warnings",
    ],
  },
];
